// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvhlrmsugmcdhsaltygg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2aGxybXN1Z21jZGhzYWx0eWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNjAyMjEsImV4cCI6MjA3NzkzNjIyMX0.F-CfGPDzehGkCVKUGYFAaUGa7xdbvsH7f07oK5yR2W8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
  global: {
    headers: {
      'X-Client-Info': 'boundless-health-app',
    },
    fetch: async (url, options = {}) => {
      let lastError: Error | null = null;
      const maxRetries = 3;
      const retryDelay = 1000;

      for (let attempt = 0; attempt < maxRetries; attempt++) {
        try {
          const response = await fetch(url, {
            ...options,
            timeout: 30000,
          } as RequestInit);
          return response;
        } catch (error) {
          lastError = error as Error;
          if (error instanceof TypeError && error.message.includes('Failed to fetch')) {
            if (attempt < maxRetries - 1) {
              await new Promise(resolve => setTimeout(resolve, retryDelay * Math.pow(2, attempt)));
              continue;
            }
          }
          throw error;
        }
      }

      throw lastError || new Error('Network request failed after retries');
    },
  },
});
